-- Non-destructive PostgreSQL migration for vehicle maintenance and reminders.
-- The application still uses Hibernate ddl-auto=update for local development.

ALTER TABLE vehicles
    ADD COLUMN IF NOT EXISTS notes VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    maintenance_type VARCHAR(40) NOT NULL,
    maintenance_date DATE NOT NULL,
    mileage INTEGER NOT NULL,
    cost NUMERIC(12, 2),
    note VARCHAR(1000),
    next_recommended_date DATE,
    next_recommended_mileage INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_maintenance_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE,
    CONSTRAINT fk_maintenance_creator
        FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    CONSTRAINT ck_maintenance_mileage CHECK (mileage BETWEEN 0 AND 2000000),
    CONSTRAINT ck_maintenance_next_mileage
        CHECK (next_recommended_mileage IS NULL OR next_recommended_mileage BETWEEN 0 AND 2000000),
    CONSTRAINT ck_maintenance_cost CHECK (cost IS NULL OR cost >= 0)
);

CREATE INDEX IF NOT EXISTS idx_maintenance_vehicle_date
    ON maintenance_records (vehicle_id, maintenance_date DESC);

CREATE TABLE IF NOT EXISTS vehicle_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    reminder_type VARCHAR(40) NOT NULL,
    title VARCHAR(120),
    due_date DATE,
    due_mileage INTEGER,
    note VARCHAR(1000),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reminder_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE,
    CONSTRAINT fk_reminder_creator
        FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    CONSTRAINT ck_reminder_due CHECK (due_date IS NOT NULL OR due_mileage IS NOT NULL),
    CONSTRAINT ck_reminder_mileage
        CHECK (due_mileage IS NULL OR due_mileage BETWEEN 0 AND 2000000)
);

CREATE INDEX IF NOT EXISTS idx_reminder_vehicle_due
    ON vehicle_reminders (vehicle_id, completed_at, due_date);

CREATE TABLE IF NOT EXISTS vehicle_mileage_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    recorded_by_user_id BIGINT NOT NULL,
    previous_mileage INTEGER,
    new_mileage INTEGER NOT NULL,
    recorded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_mileage_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE,
    CONSTRAINT fk_mileage_recorder
        FOREIGN KEY (recorded_by_user_id) REFERENCES users (id),
    CONSTRAINT ck_mileage_previous
        CHECK (previous_mileage IS NULL OR previous_mileage BETWEEN 0 AND 2000000),
    CONSTRAINT ck_mileage_new CHECK (new_mileage BETWEEN 0 AND 2000000)
);

CREATE INDEX IF NOT EXISTS idx_mileage_vehicle_recorded_at
    ON vehicle_mileage_records (vehicle_id, recorded_at DESC);
