-- Non-destructive PostgreSQL migration for rewarded analyses and notifications.

CREATE TABLE IF NOT EXISTS rewarded_analysis_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    month_start DATE NOT NULL,
    token VARCHAR(36) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    transaction_id VARCHAR(128),
    claimed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reward_session_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_reward_user_month UNIQUE (user_id, month_start),
    CONSTRAINT uk_reward_token UNIQUE (token),
    CONSTRAINT uk_reward_transaction UNIQUE (transaction_id)
);

CREATE TABLE IF NOT EXISTS device_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(512) NOT NULL,
    platform VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_device_token_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_device_token UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS idx_device_token_user_active
    ON device_tokens (user_id, active);

CREATE TABLE IF NOT EXISTS app_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    vehicle_id BIGINT,
    reminder_id BIGINT,
    event_key VARCHAR(160) NOT NULL,
    notification_type VARCHAR(40) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(160) NOT NULL,
    body VARCHAR(500) NOT NULL,
    navigation_target VARCHAR(200),
    read_at TIMESTAMP,
    push_attempted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_notification_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_reminder FOREIGN KEY (reminder_id) REFERENCES vehicle_reminders (id) ON DELETE SET NULL,
    CONSTRAINT uk_notification_user_event UNIQUE (user_id, event_key)
);

CREATE INDEX IF NOT EXISTS idx_notification_user_created
    ON app_notifications (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notification_user_unread
    ON app_notifications (user_id, read_at);
