--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4




--
-- Name: app_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_notifications (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    push_attempted_at timestamp(6) without time zone,
    read_at timestamp(6) without time zone,
    reminder_id bigint,
    user_id bigint NOT NULL,
    vehicle_id bigint,
    severity character varying(20) NOT NULL,
    notification_type character varying(40) NOT NULL,
    event_key character varying(160) NOT NULL,
    title character varying(160) NOT NULL,
    navigation_target character varying(200),
    body character varying(500) NOT NULL,
    CONSTRAINT app_notifications_notification_type_check CHECK (((notification_type)::text = 'VEHICLE_REMINDER'::text)),
    CONSTRAINT app_notifications_severity_check CHECK (((severity)::text = ANY ((ARRAY['INFO'::character varying, 'WARNING'::character varying, 'CRITICAL'::character varying])::text[])))
);


--
-- Name: app_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: billing_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.billing_subscriptions (
    auto_renewing boolean NOT NULL,
    sandbox boolean NOT NULL,
    current_period_ends_at timestamp(6) without time zone,
    current_period_started_at timestamp(6) without time zone,
    id bigint NOT NULL,
    last_synced_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    status character varying(30) NOT NULL,
    store character varying(30),
    product_id character varying(100),
    management_url character varying(500),
    CONSTRAINT billing_subscriptions_status_check CHECK (((status)::text = ANY ((ARRAY['NONE'::character varying, 'ACTIVE'::character varying, 'CANCELLED'::character varying, 'BILLING_ISSUE'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: billing_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.billing_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.billing_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: billing_webhook_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.billing_webhook_events (
    id bigint NOT NULL,
    processed_at timestamp(6) without time zone NOT NULL,
    event_type character varying(50) NOT NULL,
    app_user_id character varying(100),
    provider_event_id character varying(100) NOT NULL
);


--
-- Name: billing_webhook_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.billing_webhook_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.billing_webhook_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_accounts (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    company_name character varying(150) NOT NULL
);


--
-- Name: business_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.business_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_invitations (
    business_account_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    code_hash character varying(255) NOT NULL
);


--
-- Name: business_invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.business_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_members (
    business_account_id bigint NOT NULL,
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    role character varying(20) NOT NULL,
    CONSTRAINT business_members_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'MEMBER'::character varying])::text[])))
);


--
-- Name: business_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.business_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: damage_detections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.damage_detections (
    confidence double precision NOT NULL,
    x1 double precision NOT NULL,
    x2 double precision NOT NULL,
    y1 double precision NOT NULL,
    y2 double precision NOT NULL,
    id bigint NOT NULL,
    inspection_id bigint NOT NULL,
    affected_part character varying(50),
    label character varying(100) NOT NULL,
    CONSTRAINT damage_detections_affected_part_check CHECK (((affected_part)::text = ANY ((ARRAY['UNKNOWN'::character varying, 'FRONT_BUMPER'::character varying, 'REAR_BUMPER'::character varying, 'FRONT_DOOR'::character varying, 'REAR_DOOR'::character varying, 'FRONT_WHEEL'::character varying, 'REAR_WHEEL'::character varying, 'FRONT_WINDOW'::character varying, 'REAR_WINDOW'::character varying, 'WINDSHIELD'::character varying, 'REAR_WINDSHIELD'::character varying, 'FENDER'::character varying, 'QUARTER_PANEL'::character varying, 'ROCKER_PANEL'::character varying, 'GRILLE'::character varying, 'HEADLIGHT'::character varying, 'TAIL_LIGHT'::character varying, 'HOOD'::character varying, 'LICENSE_PLATE'::character varying, 'MIRROR'::character varying, 'ROOF'::character varying, 'TRUNK'::character varying])::text[])))
);


--
-- Name: damage_detections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.damage_detections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.damage_detections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: damage_inspections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.damage_inspections (
    confidence_score double precision,
    location_latitude double precision,
    location_longitude double precision,
    analysis_started_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    damage_severity character varying(30),
    report_status character varying(30),
    status character varying(30) NOT NULL,
    location_city character varying(100),
    image_path character varying(500),
    analysis_message character varying(1000),
    report_message character varying(1000),
    CONSTRAINT damage_inspections_damage_severity_check CHECK (((damage_severity)::text = ANY ((ARRAY['UNKNOWN'::character varying, 'NONE'::character varying, 'MINOR'::character varying, 'MODERATE'::character varying, 'SEVERE'::character varying])::text[]))),
    CONSTRAINT damage_inspections_report_status_check CHECK (((report_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT damage_inspections_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: damage_inspections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.damage_inspections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.damage_inspections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: damage_recommendation_parts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.damage_recommendation_parts (
    recommendation_id bigint NOT NULL,
    vehicle_part character varying(50) NOT NULL,
    CONSTRAINT damage_recommendation_parts_vehicle_part_check CHECK (((vehicle_part)::text = ANY ((ARRAY['UNKNOWN'::character varying, 'FRONT_BUMPER'::character varying, 'REAR_BUMPER'::character varying, 'FRONT_DOOR'::character varying, 'REAR_DOOR'::character varying, 'FRONT_WHEEL'::character varying, 'REAR_WHEEL'::character varying, 'FRONT_WINDOW'::character varying, 'REAR_WINDOW'::character varying, 'WINDSHIELD'::character varying, 'REAR_WINDSHIELD'::character varying, 'FENDER'::character varying, 'QUARTER_PANEL'::character varying, 'ROCKER_PANEL'::character varying, 'GRILLE'::character varying, 'HEADLIGHT'::character varying, 'TAIL_LIGHT'::character varying, 'HOOD'::character varying, 'LICENSE_PLATE'::character varying, 'MIRROR'::character varying, 'ROOF'::character varying, 'TRUNK'::character varying])::text[])))
);


--
-- Name: damage_repair_recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.damage_repair_recommendations (
    part_replacement_required boolean CONSTRAINT damage_repair_recommendation_part_replacement_required_not_null NOT NULL,
    id bigint NOT NULL,
    inspection_id bigint NOT NULL,
    damage_type character varying(50) NOT NULL,
    recommended_action character varying(50) NOT NULL,
    CONSTRAINT damage_repair_recommendations_damage_type_check CHECK (((damage_type)::text = ANY ((ARRAY['NO_VISIBLE_DAMAGE'::character varying, 'SCRATCH'::character varying, 'PAINT_DAMAGE'::character varying, 'DENT'::character varying, 'CRACK'::character varying, 'BROKEN_PART'::character varying, 'BROKEN_GLASS'::character varying, 'DEFORMATION'::character varying])::text[]))),
    CONSTRAINT damage_repair_recommendations_recommended_action_check CHECK (((recommended_action)::text = ANY ((ARRAY['NO_ACTION'::character varying, 'POLISHING'::character varying, 'PAINT_TOUCH_UP'::character varying, 'FULL_PAINTING'::character varying, 'PAINTLESS_DENT_REPAIR'::character varying, 'DENT_REPAIR'::character varying, 'PLASTIC_REPAIR'::character varying, 'PART_REPAIR'::character varying, 'PART_REPLACEMENT'::character varying, 'GLASS_REPAIR'::character varying, 'GLASS_REPLACEMENT'::character varying, 'HEADLIGHT_REPAIR'::character varying, 'HEADLIGHT_REPLACEMENT'::character varying])::text[])))
);


--
-- Name: damage_repair_recommendations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.damage_repair_recommendations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.damage_repair_recommendations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device_tokens (
    active boolean NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    platform character varying(20) NOT NULL,
    token character varying(512) NOT NULL,
    CONSTRAINT device_tokens_platform_check CHECK (((platform)::text = ANY ((ARRAY['ANDROID'::character varying, 'IOS'::character varying])::text[])))
);


--
-- Name: device_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.device_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inspection_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inspection_reports (
    estimated_maximum_price numeric(12,2),
    estimated_minimum_price numeric(12,2),
    generated_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    inspection_id bigint NOT NULL,
    currency character varying(10),
    title character varying(200) NOT NULL,
    disclaimer character varying(1500) NOT NULL,
    summary character varying(1500) NOT NULL,
    price_source_description character varying(2000),
    damage_description character varying(3000) NOT NULL,
    price_information character varying(3000),
    repair_recommendation character varying(3000) NOT NULL
);


--
-- Name: inspection_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inspection_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspection_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maintenance_records (
    cost numeric(12,2),
    interval_mileage integer,
    interval_months integer,
    maintenance_date date NOT NULL,
    mileage integer NOT NULL,
    next_recommended_date date,
    next_recommended_mileage integer,
    created_at timestamp(6) without time zone NOT NULL,
    created_by_user_id bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    vehicle_id bigint NOT NULL,
    maintenance_type character varying(40) NOT NULL,
    note character varying(1000),
    CONSTRAINT maintenance_records_maintenance_type_check CHECK (((maintenance_type)::text = ANY ((ARRAY['ENGINE_OIL'::character varying, 'OIL_FILTER'::character varying, 'AIR_FILTER'::character varying, 'CABIN_FILTER'::character varying, 'BRAKE_PADS'::character varying, 'BRAKE_FLUID'::character varying, 'BATTERY'::character varying, 'TIRES'::character varying, 'TIMING_SYSTEM'::character varying, 'TRANSMISSION'::character varying, 'PERIODIC_MAINTENANCE'::character varying, 'CUSTOM'::character varying])::text[])))
);


--
-- Name: maintenance_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.maintenance_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_codes (
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    code_hash character varying(100) NOT NULL
);


--
-- Name: password_reset_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pending_registrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pending_registrations (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    verification_code_expires_at timestamp(6) without time zone NOT NULL,
    full_name character varying(100) NOT NULL,
    password_hash character varying(100) NOT NULL,
    verification_code_hash character varying(100) NOT NULL,
    email character varying(150) NOT NULL
);


--
-- Name: pending_registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pending_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pending_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    email_verified boolean DEFAULT true NOT NULL,
    email_verification_code_expires_at timestamp(6) without time zone,
    id bigint NOT NULL,
    subscription_expires_at timestamp(6) without time zone,
    subscription_started_at timestamp(6) without time zone,
    subscription_plan character varying(20) NOT NULL,
    billing_customer_id character varying(36),
    email_verification_code_hash character varying(100),
    full_name character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    CONSTRAINT users_subscription_plan_check CHECK (((subscription_plan)::text = ANY ((ARRAY['FREE'::character varying, 'PLUS'::character varying, 'PRO'::character varying, 'BUSINESS'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle_mileage_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_mileage_records (
    new_mileage integer NOT NULL,
    previous_mileage integer,
    id bigint NOT NULL,
    recorded_at timestamp(6) without time zone NOT NULL,
    recorded_by_user_id bigint NOT NULL,
    vehicle_id bigint NOT NULL
);


--
-- Name: vehicle_mileage_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehicle_mileage_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_mileage_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle_reminders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_reminders (
    due_date date,
    due_mileage integer,
    first_inspection boolean,
    interval_mileage integer,
    interval_months integer,
    source_date date,
    source_mileage integer,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    created_by_user_id bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    vehicle_id bigint NOT NULL,
    reminder_type character varying(40) NOT NULL,
    title character varying(120),
    note character varying(1000),
    CONSTRAINT vehicle_reminders_reminder_type_check CHECK (((reminder_type)::text = ANY ((ARRAY['PERIODIC_MAINTENANCE'::character varying, 'VEHICLE_INSPECTION'::character varying, 'TRAFFIC_INSURANCE'::character varying, 'COMPREHENSIVE_INSURANCE'::character varying, 'TIRE_CHECK'::character varying, 'CUSTOM'::character varying])::text[])))
);


--
-- Name: vehicle_reminders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehicle_reminders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_reminders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles (
    archived boolean NOT NULL,
    mileage integer NOT NULL,
    model_year integer NOT NULL,
    primary_vehicle boolean NOT NULL,
    business_account_id bigint,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint,
    plate character varying(20) NOT NULL,
    brand character varying(50) NOT NULL,
    model character varying(50) NOT NULL,
    notes character varying(1000)
);


--
-- Name: vehicles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_notifications app_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_notifications
    ADD CONSTRAINT app_notifications_pkey PRIMARY KEY (id);


--
-- Name: billing_subscriptions billing_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.billing_subscriptions
    ADD CONSTRAINT billing_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: billing_subscriptions billing_subscriptions_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.billing_subscriptions
    ADD CONSTRAINT billing_subscriptions_user_id_key UNIQUE (user_id);


--
-- Name: billing_webhook_events billing_webhook_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.billing_webhook_events
    ADD CONSTRAINT billing_webhook_events_pkey PRIMARY KEY (id);


--
-- Name: business_accounts business_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_accounts
    ADD CONSTRAINT business_accounts_pkey PRIMARY KEY (id);


--
-- Name: business_invitations business_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_invitations
    ADD CONSTRAINT business_invitations_pkey PRIMARY KEY (id);


--
-- Name: business_members business_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_members
    ADD CONSTRAINT business_members_pkey PRIMARY KEY (id);


--
-- Name: business_members business_members_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_members
    ADD CONSTRAINT business_members_user_id_key UNIQUE (user_id);


--
-- Name: damage_detections damage_detections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.damage_detections
    ADD CONSTRAINT damage_detections_pkey PRIMARY KEY (id);


--
-- Name: damage_inspections damage_inspections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.damage_inspections
    ADD CONSTRAINT damage_inspections_pkey PRIMARY KEY (id);


--
-- Name: damage_recommendation_parts damage_recommendation_parts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.damage_recommendation_parts
    ADD CONSTRAINT damage_recommendation_parts_pkey PRIMARY KEY (recommendation_id, vehicle_part);


--
-- Name: damage_repair_recommendations damage_repair_recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.damage_repair_recommendations
    ADD CONSTRAINT damage_repair_recommendations_pkey PRIMARY KEY (id);


--
-- Name: device_tokens device_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_pkey PRIMARY KEY (id);


--
-- Name: inspection_reports inspection_reports_inspection_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inspection_reports
    ADD CONSTRAINT inspection_reports_inspection_id_key UNIQUE (inspection_id);


--
-- Name: inspection_reports inspection_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inspection_reports
    ADD CONSTRAINT inspection_reports_pkey PRIMARY KEY (id);


--
-- Name: maintenance_records maintenance_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_records
    ADD CONSTRAINT maintenance_records_pkey PRIMARY KEY (id);


--
-- Name: password_reset_codes password_reset_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_codes
    ADD CONSTRAINT password_reset_codes_pkey PRIMARY KEY (id);


--
-- Name: password_reset_codes password_reset_codes_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_codes
    ADD CONSTRAINT password_reset_codes_user_id_key UNIQUE (user_id);


--
-- Name: pending_registrations pending_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_registrations
    ADD CONSTRAINT pending_registrations_pkey PRIMARY KEY (id);


--
-- Name: billing_webhook_events uk_billing_webhook_event_provider_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.billing_webhook_events
    ADD CONSTRAINT uk_billing_webhook_event_provider_id UNIQUE (provider_event_id);


--
-- Name: business_invitations uk_business_invitation_business_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_invitations
    ADD CONSTRAINT uk_business_invitation_business_user UNIQUE (business_account_id, user_id);


--
-- Name: device_tokens uk_device_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT uk_device_token UNIQUE (token);


--
-- Name: app_notifications uk_notification_user_event; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_notifications
    ADD CONSTRAINT uk_notification_user_event UNIQUE (user_id, event_key);


--
-- Name: pending_registrations uk_pending_registration_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_registrations
    ADD CONSTRAINT uk_pending_registration_email UNIQUE (email);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: users users_billing_customer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_billing_customer_id_key UNIQUE (billing_customer_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vehicle_mileage_records vehicle_mileage_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_mileage_records
    ADD CONSTRAINT vehicle_mileage_records_pkey PRIMARY KEY (id);


--
-- Name: vehicle_reminders vehicle_reminders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_reminders
    ADD CONSTRAINT vehicle_reminders_pkey PRIMARY KEY (id);


--
-- Name: vehicles vehicles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);


--
-- Name: vehicles vehicles_plate_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_plate_key UNIQUE (plate);


--
-- Name: business_invitations fk4kxvawgyaakj45egt820b9hyw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_invitations
    ADD CONSTRAINT fk4kxvawgyaakj45egt820b9hyw FOREIGN KEY (business_account_id) REFERENCES public.business_accounts(id);


--
-- Name: damage_detections fk_detection_inspection; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.damage_detections
    ADD CONSTRAINT fk_detection_inspection FOREIGN KEY (inspection_id) REFERENCES public.damage_inspections(id);


--
-- Name: damage_inspections fk_inspection_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.damage_inspections
    ADD CONSTRAINT fk_inspection_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: damage_inspections fk_inspection_vehicle; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.damage_inspections
    ADD CONSTRAINT fk_inspection_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);


--
-- Name: damage_repair_recommendations fk_recommendation_inspection; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.damage_repair_recommendations
    ADD CONSTRAINT fk_recommendation_inspection FOREIGN KEY (inspection_id) REFERENCES public.damage_inspections(id);


--
-- Name: damage_recommendation_parts fk_recommendation_part; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.damage_recommendation_parts
    ADD CONSTRAINT fk_recommendation_part FOREIGN KEY (recommendation_id) REFERENCES public.damage_repair_recommendations(id);


--
-- Name: inspection_reports fk_report_inspection; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inspection_reports
    ADD CONSTRAINT fk_report_inspection FOREIGN KEY (inspection_id) REFERENCES public.damage_inspections(id);


--
-- Name: vehicles fk_vehicle_business_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT fk_vehicle_business_account FOREIGN KEY (business_account_id) REFERENCES public.business_accounts(id);


--
-- Name: vehicles fk_vehicle_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT fk_vehicle_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: business_members fkc9c83aqwkjmk58ftk0klrhxs9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_members
    ADD CONSTRAINT fkc9c83aqwkjmk58ftk0klrhxs9 FOREIGN KEY (business_account_id) REFERENCES public.business_accounts(id);


--
-- Name: business_invitations fke9un8r6t9wmnb353llp9am138; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_invitations
    ADD CONSTRAINT fke9un8r6t9wmnb353llp9am138 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: app_notifications fkg64v68jxyvxh8x2ddfktw30n0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_notifications
    ADD CONSTRAINT fkg64v68jxyvxh8x2ddfktw30n0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: vehicle_reminders fkgmvvf9r7uytrd3i1dnx9h9wml; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_reminders
    ADD CONSTRAINT fkgmvvf9r7uytrd3i1dnx9h9wml FOREIGN KEY (created_by_user_id) REFERENCES public.users(id);


--
-- Name: device_tokens fkhc7d11bnr8x9gs5biohdhnx1c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT fkhc7d11bnr8x9gs5biohdhnx1c FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: app_notifications fki21mf5ypwvka1m6uy7onp1euv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_notifications
    ADD CONSTRAINT fki21mf5ypwvka1m6uy7onp1euv FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);


--
-- Name: password_reset_codes fkke97isexxbl8lf7yibo6q02ir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_codes
    ADD CONSTRAINT fkke97isexxbl8lf7yibo6q02ir FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: business_members fkl3se6j2mob8wdx6tjckpx0qjt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_members
    ADD CONSTRAINT fkl3se6j2mob8wdx6tjckpx0qjt FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: vehicle_mileage_records fklx3m4spa4ddqanx99t3lwfpnn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_mileage_records
    ADD CONSTRAINT fklx3m4spa4ddqanx99t3lwfpnn FOREIGN KEY (recorded_by_user_id) REFERENCES public.users(id);


--
-- Name: vehicle_reminders fklxi9gm463xlaaate4dh7fvq5j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_reminders
    ADD CONSTRAINT fklxi9gm463xlaaate4dh7fvq5j FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);


--
-- Name: maintenance_records fko3vq8jhaakqmbvlhn7oo0x7y3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_records
    ADD CONSTRAINT fko3vq8jhaakqmbvlhn7oo0x7y3 FOREIGN KEY (created_by_user_id) REFERENCES public.users(id);


--
-- Name: vehicle_mileage_records fkpni2cc1mb5pusq9puy30s3fe3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_mileage_records
    ADD CONSTRAINT fkpni2cc1mb5pusq9puy30s3fe3 FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);


--
-- Name: maintenance_records fkr0tdwm72b9ldf2jvxq875nay2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_records
    ADD CONSTRAINT fkr0tdwm72b9ldf2jvxq875nay2 FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);


--
-- Name: billing_subscriptions fksrgx4jgvvbmw64h1djlg906d0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.billing_subscriptions
    ADD CONSTRAINT fksrgx4jgvvbmw64h1djlg906d0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--


