CREATE TABLE analysis_usages (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 user_id BIGINT,
                                 business_account_id BIGINT,

                                 started_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

                                 CONSTRAINT fk_analysis_usage_user
                                     FOREIGN KEY (user_id)
                                         REFERENCES users(id),

                                 CONSTRAINT fk_analysis_usage_business
                                     FOREIGN KEY (business_account_id)
                                         REFERENCES business_accounts(id),

                                 CONSTRAINT chk_analysis_usage_owner
                                     CHECK (
                                         (user_id IS NOT NULL AND business_account_id IS NULL)
                                             OR
                                         (user_id IS NULL AND business_account_id IS NOT NULL)
                                         )
);

CREATE INDEX idx_analysis_usage_user_started
    ON analysis_usages (
                        user_id,
                        started_at
        );

CREATE INDEX idx_analysis_usage_business_started
    ON analysis_usages (
                        business_account_id,
                        started_at
        );

INSERT INTO analysis_usages (
    user_id,
    business_account_id,
    started_at
)
SELECT
    CASE
        WHEN v.business_account_id IS NULL
            THEN di.user_id
        ELSE NULL
        END,
    v.business_account_id,
    di.analysis_started_at
FROM damage_inspections di
         JOIN vehicles v
              ON v.id = di.vehicle_id
WHERE di.analysis_started_at IS NOT NULL;