ALTER TABLE damage_inspections
    ADD COLUMN report_access_granted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN report_access_source VARCHAR(30);

UPDATE damage_inspections
SET report_access_granted = TRUE,
    report_access_source = CASE
        WHEN report IS NOT NULL THEN 'FREE_MONTHLY'
        ELSE report_access_source
    END
WHERE report IS NOT NULL;

CREATE TABLE analysis_credit_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    amount INTEGER NOT NULL,
    product_id VARCHAR(120),
    external_transaction_id VARCHAR(200),
    inspection_id BIGINT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_analysis_credit_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_analysis_credit_inspection FOREIGN KEY (inspection_id) REFERENCES damage_inspections(id),
    CONSTRAINT uk_analysis_credit_external_transaction UNIQUE (external_transaction_id),
    CONSTRAINT chk_analysis_credit_amount CHECK (amount <> 0)
);

CREATE INDEX idx_analysis_credit_user_created
    ON analysis_credit_transactions(user_id, created_at);
