CREATE TABLE damage_assessment_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id BIGINT NOT NULL,
    record_number VARCHAR(50) NOT NULL,
    incident_date_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    incident_city VARCHAR(100) NOT NULL,
    incident_district VARCHAR(100),
    incident_address VARCHAR(500),
    incident_description VARCHAR(3000) NOT NULL,
    declarant_full_name VARCHAR(150) NOT NULL,
    status VARCHAR(20) NOT NULL,
    document_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    finalized_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_damage_assessment_record_inspection
        FOREIGN KEY (inspection_id) REFERENCES damage_inspections(id) ON DELETE CASCADE,
    CONSTRAINT uk_damage_assessment_record_inspection UNIQUE (inspection_id),
    CONSTRAINT uk_damage_assessment_record_number UNIQUE (record_number),
    CONSTRAINT chk_damage_assessment_record_status
        CHECK (status IN ('DRAFT', 'FINALIZED')),
    CONSTRAINT chk_damage_assessment_record_version
        CHECK (document_version >= 1)
);

CREATE INDEX idx_damage_assessment_record_status
    ON damage_assessment_records(status);
