CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE ai_assistant_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    status VARCHAR(24) NOT NULL DEFAULT 'INACTIVE',
    trial_started_at TIMESTAMP(6) WITHOUT TIME ZONE,
    trial_expires_at TIMESTAMP(6) WITHOUT TIME ZONE,
    subscription_started_at TIMESTAMP(6) WITHOUT TIME ZONE,
    subscription_expires_at TIMESTAMP(6) WITHOUT TIME ZONE,
    locked_until TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_assistant_access_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_ai_assistant_access_status CHECK (
        status IN ('INACTIVE', 'TRIAL', 'ACTIVE', 'LOCKED', 'EXPIRED')
    )
);

CREATE TABLE ai_assistant_daily_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    usage_date DATE NOT NULL,
    successful_questions INTEGER NOT NULL DEFAULT 0,
    out_of_scope_attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_assistant_daily_usage_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_ai_assistant_daily_usage UNIQUE (user_id, usage_date),
    CONSTRAINT chk_ai_assistant_successful_questions CHECK (successful_questions >= 0),
    CONSTRAINT chk_ai_assistant_out_of_scope_attempts CHECK (out_of_scope_attempts >= 0)
);

CREATE TABLE ai_knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(160) NOT NULL UNIQUE,
    title VARCHAR(240) NOT NULL,
    category VARCHAR(80) NOT NULL,
    source_name VARCHAR(240),
    source_url VARCHAR(1000),
    source_version VARCHAR(80),
    content_hash VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_knowledge_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    token_count INTEGER,
    embedding VECTOR(384) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_knowledge_chunk_document
        FOREIGN KEY (document_id) REFERENCES ai_knowledge_documents(id) ON DELETE CASCADE,
    CONSTRAINT uk_ai_knowledge_chunk_index UNIQUE (document_id, chunk_index),
    CONSTRAINT chk_ai_knowledge_chunk_index CHECK (chunk_index >= 0)
);

CREATE INDEX idx_ai_knowledge_chunks_embedding
    ON ai_knowledge_chunks
    USING hnsw (embedding vector_cosine_ops);

CREATE INDEX idx_ai_knowledge_documents_category
    ON ai_knowledge_documents(category)
    WHERE active = TRUE;

CREATE TABLE ai_chat_sessions (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    vehicle_id BIGINT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_chat_session_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ai_chat_session_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

CREATE INDEX idx_ai_chat_sessions_user_updated
    ON ai_chat_sessions(user_id, updated_at DESC);

CREATE TABLE ai_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    intent VARCHAR(64),
    retrieval_used BOOLEAN NOT NULL DEFAULT FALSE,
    tool_names JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_chat_message_session
        FOREIGN KEY (session_id) REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
    CONSTRAINT chk_ai_chat_message_role CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM'))
);

CREATE INDEX idx_ai_chat_messages_session_created
    ON ai_chat_messages(session_id, created_at);

COMMENT ON COLUMN ai_knowledge_chunks.embedding IS
    '384-dimensional multilingual semantic embedding. User/private data must never be stored here.';
