// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4hdtu4HtVcEn-o8dCMTLCHH8QF5GPfiM',
    appId: '1:129219400982:web:7231edd6e193321ddd6c37',
    messagingSenderId: '129219400982',
    projectId: 'ekspersiz',
    authDomain: 'ekspersiz.firebaseapp.com',
    storageBucket: 'ekspersiz.firebasestorage.app',
    measurementId: 'G-9P4ZK3M441',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBkmphAjEjg6BIwLDIt_j1iif8p9_PjSs',
    appId: '1:129219400982:android:b83f3d8f3c02a99cdd6c37',
    messagingSenderId: '129219400982',
    projectId: 'ekspersiz',
    storageBucket: 'ekspersiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3VV1FuMyedLGJeHKS1h-mfAzUq4hEEU',
    appId: '1:129219400982:ios:1fdf7611681b38bbdd6c37',
    messagingSenderId: '129219400982',
    projectId: 'ekspersiz',
    storageBucket: 'ekspersiz.firebasestorage.app',
    iosBundleId: 'com.gorkem.ekspersiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj3VV1FuMyedLGJeHKS1h-mfAzUq4hEEU',
    appId: '1:129219400982:ios:f9c728eb21ef148edd6c37',
    messagingSenderId: '129219400982',
    projectId: 'ekspersiz',
    storageBucket: 'ekspersiz.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4hdtu4HtVcEn-o8dCMTLCHH8QF5GPfiM',
    appId: '1:129219400982:web:c8dd8f97ed2a065fdd6c37',
    messagingSenderId: '129219400982',
    projectId: 'ekspersiz',
    authDomain: 'ekspersiz.firebaseapp.com',
    storageBucket: 'ekspersiz.firebasestorage.app',
    measurementId: 'G-6QK2X03VX8',
  );
}
